@extends('layouts.public')

@section('content')
<div class="mx-auto max-w-3xl px-4 py-16 lg:px-8">
    <h1 class="text-3xl font-bold">Affiliate Program</h1>
    <div class="prose prose-invert mt-6 max-w-none space-y-4 text-text-muted">
        <p>Share your referral link and earn a share of trading fees generated by users you refer. Every registered user gets a unique referral code automatically — find yours under <a href="/app/referrals" class="text-brand hover:underline">Referrals</a> once logged in.</p>
        <ul class="list-disc space-y-2 pl-5">
            <li>Track referred signups and their KYC/trading status.</li>
            <li>View simulated commission accrual per referred user.</li>
            <li>Commission payouts will run through the same double-entry ledger as all other balance changes.</li>
        </ul>
    </div>
    <a href="{{ route('register') }}" class="btn-brand mt-8 inline-flex">Join the Affiliate Program</a>
</div>
@endsection
